#!/bin/bash -e
start_time="$(date +%s)"
source_dir="./test/test_files/"
output_dir="./test/manual/test_plot_script_results/"
clear
mkdir -p $output_dir
echo Other Scatter Overlay
python ./cis.py plot RVOD_liq_water_content:${source_dir}2007180125457_06221_CS_2B-CWC-RVOD_GRANULE_P_R04_E02.hdf RVOD_ice_water_content:${source_dir}2007180125457_06221_CS_2B-CWC-RVOD_GRANULE_P_R04_E02.hdf::s:overiddenlabel --type scatteroverlay --xlabel overiddenx --ylabel overiddeny --itemwidth 200 --fontsize 15 --height 10 --width 10 --xmin=-50 --xmax 50 --ymin 0 --ymax 15000 --vmin=-0.006 --vmax 0.003 --vstep 0.003 --cbarorient Vertical --grid --xaxis latitude --yaxis altitude --output "${output_dir}otherscatteroverlay"
end_time="$(($(date +%s)-start_time))"
echo "Time taken: ${end_time}s"
