#!/bin/bash -e
start_time="$(date +%s)"
source_dir="./test/test_files/"
output_dir="./test/manual/test_plot_script_results/"
clear
if [ -d $output_dir ]; then
    rm -r $output_dir
fi
mkdir -p $output_dir
echo Iris Contour
python ./cis.py plot rain:${source_dir}xglnwa.pm.k8dec-k9nov.col.tm.nc --type contour --cmap RdBu --xlabel "Overidden X Label" --title "Overidded Title" --height 5 --width 5 --xmin 15 --xmax 45 --xstep 20 --cbarorient vertical --fontsize 10 --output "${output_dir}iriscontour"
echo Iris Contourf
python ./cis.py plot rain:${source_dir}xglnwa.pm.k8dec-k9nov.col.tm.nc --type contourf --ylabel "Overidden Y Label" --height 5 --width 10 --ymin 15 --ymax 45 --ystep 10 --nocolourbar --output "${output_dir}iriscontourf"
echo Iris Heatmap
python ./cis.py plot rain:${source_dir}xglnwa.pm.k8dec-k9nov.col.tm.nc --type heatmap --cmap RdBu --ylabel OveriddenY --title OveriddenTitle --vmax 0.000135 --fontsize 10 --height 3.5 --cbarorient horizontal --output "${output_dir}irisheatmap"
echo Iris one line
python ./cis.py plot rain:${source_dir}xglnwa.pm.k8dec-k9nov.vprof.tm.nc::dashed:overiddenlabel --xlabel overiddenxlabel --title overiddentitle --itemwidth 4 --height 5 --width 10 --logy --grid --output "${output_dir}irisoneline"
echo Iris many lines
python ./cis.py plot rain:${source_dir}xglnwa.pm.k8dec-k9nov.vprof.tm.nc:red snow:${source_dir}xglnwa.pm.k8dec-k9nov.vprof.tm.nc::dashed:overiddenlabel2 --xlabel overiddenxlabel --ylabel overiddenylabel --itemwidth 5 --width 10 --logx --grid --xmin 0.00000000001 --ymax 50 --output "${output_dir}irismanylines"
echo Iris Scatter 2D
python ./cis.py plot rain:${source_dir}xglnwa.pm.k8dec-k9nov.vprof.tm.nc::^: --type scatter --title overiddentitle --fontsize 10 --width 7 --itemwidth 300 --xmin=-0.0005 --xmax 0.0005 --output "${output_dir}irisscatter2d"
echo Iris Scatter 3D
python ./cis.py plot rain:${source_dir}xglnwa.pm.k8dec-k9nov.col.tm.nc snow:${source_dir}xglnwa.pm.k8dec-k9nov.col.tm.nc:::snowlabel --type scatter --cmap RdBu --fontsize 7 --cbarorient vertical --grid --ymin 0 --ymax 90 --vmin 0 --cbarorient vertical --output "${output_dir}irisscatter3d"
echo Iris Scatter Overlay
python ./cis.py plot rain:${source_dir}xglnwa.pm.k8dec-k9nov.col.tm.nc snow:${source_dir}xglnwa.pm.k8dec-k9nov.col.tm.nc::^:snowlabel --type scatteroverlay --xlabel overiddenxlabel --height 10 --width 12 --xmin 0 --xmax 200 --xstep 10 --cbarorient horizontal --ymin 0 --ymax 90 --vmin 0 --cbarorient horizontal --output "${output_dir}irisscatteroverlay"
echo Iris Comparative Scatter
python ./cis.py plot rain:${source_dir}xglnwa.pm.k8dec-k9nov.col.tm.nc:green:^ snow:${source_dir}xglnwa.pm.k8dec-k9nov.col.tm.nc --type comparativescatter --itemwidth 400 --logx --logy --output "${output_dir}iriscomparativescatter"
echo Iris Histogram 2D
python ./cis.py plot rain:${source_dir}xglnwa.pm.k8dec-k9nov.vprof.tm.nc:red:step:overridenlabel snow:${source_dir}xglnwa.pm.k8dec-k9nov.vprof.tm.nc:green:step --type histogram2d --xmin=-50 --xmax 50 --xstep 10 --ymin 1 --logy --output "${output_dir}irishistogram2d"
echo Iris Histogram 3D
python ./cis.py plot rain:${source_dir}xglnwa.pm.k8dec-k9nov.vprof.tm.nc snow:${source_dir}xglnwa.pm.k8dec-k9nov.vprof.tm.nc --type histogram3d --cmap RdBu --ylabel overiddeny --title overiddentitle --xmin=-50 --xmax 40 --ystep 10 --vmin 3 --vstep 1 --output "${output_dir}irishistogram3d"
echo Other Contour
python ./cis.py plot RVOD_liq_water_content:${source_dir}2007180125457_06221_CS_2B-CWC-RVOD_GRANULE_P_R04_E02.hdf --type contour --cmap RdBu --ylabel overiddenylabel --title overiddentitle --vmin 0 --cbarorient vertical --grid --xaxis latitude --yaxis altitude --output "${output_dir}othercontour"
echo Other Contourf
python ./cis.py plot RVOD_liq_water_content:${source_dir}2007180125457_06221_CS_2B-CWC-RVOD_GRANULE_P_R04_E02.hdf --type contour --xlabel overiddenxlabel --itemwidth 4 --fontsize 15 --height 10 --ymin 0 --ymax 10000 --vmin 0 --vstep 300 --cbarorient horizontal --grid --xaxis latitude --yaxis altitude --output "${output_dir}othercontourf"
echo Other Heatmap
python ./cis.py plot RVOD_liq_water_content:${source_dir}2007180125457_06221_CS_2B-CWC-RVOD_GRANULE_P_R04_E02.hdf --type heatmap --cmap RdBu --ylabel overiddenylabel --width 7 --ymin 0 --ymax 5000 --nocolourbar --grid --xaxis latitude --yaxis altitude --output "${output_dir}otherheatmap"
echo Other one line
python ./cis.py plot AOT_440:${source_dir}920801_091128_Agoufou.lev20::dashed:overiddenlabel --type line --xlabel "overiddenx" --title "overiddentitle" --itemwidth 4 --fontsize 7 --height 7 --ymin 0.1 --ymax 1 --logx --logy --output "${output_dir}otheroneline"
echo Other many lines
python ./cis.py plot AOT_440:${source_dir}920801_091128_Agoufou.lev20:green:dotted AOT_870:${source_dir}920801_091128_Agoufou.lev20::dashed AOT_1020:${source_dir}920801_091128_Agoufou.lev20:red --type line --ylabel overiddenylabel --itemwidth 2 --ymin 0.1 --ymax 1 --logx --logy --output "${output_dir}othermanylines"
echo Other Scatter 2D
python ./cis.py plot AOT_440:${source_dir}920801_091128_Agoufou.lev20 --type scatter --xlabel overiddenx --ylabel overiddeny --title overiddentitle --itemwidth 2 --fontsize 15 --height 5 --width 6 --logy --grid --output "${output_dir}otherscatter2d"
echo Other Scatter 3D
python ./cis.py plot RVOD_liq_water_content:${source_dir}2007180125457_06221_CS_2B-CWC-RVOD_GRANULE_P_R04_E02.hdf --type scatter --cmap RdBu --title overiddentitle --itemwidth 20 --vmax 175 --logy --xaxis latitude --yaxis altitude --output "${output_dir}otherscatter3d"
echo Other Scatter Overlay
python ./cis.py plot RVOD_liq_water_content:${source_dir}2007180125457_06221_CS_2B-CWC-RVOD_GRANULE_P_R04_E02.hdf RVOD_ice_water_content:${source_dir}2007180125457_06221_CS_2B-CWC-RVOD_GRANULE_P_R04_E02.hdf::s:overiddenlabel --type scatteroverlay --xlabel overiddenx --ylabel overiddeny --itemwidth 200 --fontsize 15 --height 10 --width 10 --xmin=-50 --xmax 50 --ymin 0 --ymax 15000 --vmin=-0.006 --vmax 0.003 --vstep 0.003 --cbarorient Vertical --grid --xaxis latitude --yaxis altitude --output "${output_dir}otherscatteroverlay"
echo Other Comparative Scatter
python ./cis.py plot AOT_440:${source_dir}920801_091128_Agoufou_small.lev20:red:s AOT_870:${source_dir}920801_091128_Agoufou_small.lev20 --type comparativescatter --xlabel overiddenx --ylabel overiddeny --title overiddentitle --fontsize 7 --height 5 --width 5 --xmin 0 --xmax 1 --ymin 0 --ymax 0.5 --itemwidth 400 --grid --output "${output_dir}othercomparativescatter"
echo Other Histogram 2D
python ./cis.py plot AOT_440:${source_dir}920801_091128_Agoufou_small.lev20::step --type histogram2d --xlabel overiddenx --fontsize 10 --height 10 --width 10 --xmin 0 --xmax 1.5 --xstep 0.1 --grid --output "${output_dir}otherhistogram2d"
echo Other Histogram 3D
python ./cis.py plot AOT_440:${source_dir}920801_091128_Agoufou_small.lev20 AOT_870:${source_dir}920801_091128_Agoufou_small.lev20 --type histogram3d --xlabel overridenx --ylabel overiddeny --cbarlabel overiddencbarlabel --title overiddentitle --fontsize 7 --width 10 --xmin 0 --xmax 2 --xstep 0.1 --ymin 0 --ymax 1.5 --ystep 0.1 --vmin 60 --vmax 480 --vstep 30 --cbarorient Vertical --grid --output "${output_dir}otherhistogram3d"
end_time="$(($(date +%s)-start_time))"
echo "Time taken: ${end_time}s"
